--------------------------------------------------------
--  DDL for Table PROJECTS
--------------------------------------------------------

  CREATE TABLE "HR"."PROJECTS" 
   (	"PROJECT_ID" NUMBER(6,0), 
	"PROJECT_NAME" VARCHAR2(50), 
	"DEPARTMENT_ID" NUMBER(4,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"BUDGET" NUMBER(10,2)
   ) ;

  ALTER TABLE "HR"."PROJECTS" MODIFY ("PROJECT_ID" CONSTRAINT "PROJECT_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."PROJECTS" MODIFY ("PROJECT_NAME" CONSTRAINT "PROJECT_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."PROJECTS" ADD CONSTRAINT "PROJECT_ID_PK" PRIMARY KEY ("PROJECT_ID")
  USING INDEX ENABLE;
  ALTER TABLE "HR"."PROJECTS" ADD CONSTRAINT "PROJECTS_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "HR"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
